# Generated by Django 5.0.4 on 2026-07-10 16:50

from django.db import migrations, models


def backfill_roles(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    for profile in UserProfile.objects.select_related('user').all():
        user = profile.user
        if user.is_superuser:
            continue
        if user.is_staff:
            profile.role = 'store_manager'
            profile.save(update_fields=['role'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[('customer', 'Customer'), ('store_manager', 'Store Manager')],
                default='customer',
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_roles, noop_reverse),
    ]
